export const LOGINUSERREQ = "LOGINUSERREQ";
export const LOGINUSERSUCESS = "LOGINUSERSUCESS";
export const LOGINUSERFAILURE = "LOGINUSERFAILURE";

export const LOGINUSERDATAREQ = "LOGINUSERDATAREQ";
export const LOGINUSERDATASUCESS = "LOGINUSERDATASUCESS";
export const LOGINUSERDATAFAILURE = "LOGINUSERDATAFAILURE";

