export const LOGINUSERREQ = "LOGINUSERREQ";
export const LOGINUSERSUCESS = "LOGINUSERSUCESS";
export const LOGINUSERFAILURE = "LOGINUSERFAILURE";


export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const SIGNUPUSERREQ     = "SIGNUPUSERREQ";
export const SIGNUPUSERSUCESS  = "SIGNUPUSERSUCESS";
export const SIGNUPUSERFAILURE = "SIGNUPUSERFAILURE";


export const ADMINUSERREQ = "ADMINUSERREQ";
export const ADMINUSERSUCESS = "ADMINUSERSUCESS";
export const ADMINUSERFAILURE = "ADMINUSERFAILURE";
