export const LOGINUSERREQ = "LOGINUSERREQ";
export const LOGINUSERSUCESS = "LOGINUSERSUCESS";
export const LOGINUSERFAILURE = "LOGINUSERFAILURE";


export const SIGNUPUSERREQ     = "SIGNUPUSERREQ";
export const SIGNUPUSERSUCESS  = "SIGNUPUSERSUCESS";
export const SIGNUPUSERFAILURE = "SIGNUPUSERFAILURE";
