export const GETDOCTORREQ     = "GETDOCTORREQ";
export const GETDOCTORSUCESS  = "GETDOCTORSUCESS";
export const GETDOCTORFAILURE = "GETDOCTORFAILURE";


export const GETSINGLE_DOCTOR_REQUEST = "GETSINGLE_DOCTOR_REQUEST";
export const GETSINGLE_DOCTOR_SUCCESS = "GETSINGLE_DOCTOR_SUCCESS";
export const GETSINGLE_DOCTOR_FAILURE = "GETSINGLE_DOCTOR_FAILURE";


export const GETMYAPPOINMENTREQ     = "GETMYAPPOINMENTREQ";
export const GETMYAPPOINMENTSUCESS  = "GETMYAPPOINMENTSUCESS";
export const GETMYAPPOINMENTFAILURE = "GETMYAPPOINMENTFAILURE";
