export const GETDOCTORREQ     = "GETDOCTORREQ";
export const GETDOCTORSUCESS  = "GETDOCTORSUCESS";
export const GETDOCTORFAILURE = "GETDOCTORFAILURE";


export const GETSINGLE_DOCTOR_REQUEST = "GETSINGLE_DOCTOR_REQUEST";
export const GETSINGLE_DOCTOR_SUCCESS = "GETSINGLE_DOCTOR_SUCCESS";
export const GETSINGLE_DOCTOR_FAILURE = "GETSINGLE_DOCTOR_FAILURE";


export const BOOKAPPOINMETREQ     = "BOOKAPPOINMETREQ";
export const BOOKAPPOINMETUCESS  = "BOOKAPPOINMETUCESS";
export const BOOKAPPOINMETFAILURE = "BOOKAPPOINMETFAILURE";



export const CANCELAPPOINMETREQ     = "CANCELAPPOINMETREQ";
export const CANCELAPPOINMETUCESS   = "CANCELAPPOINMETUCESS";
export const CANCELAPPOINMETFAILURE = "CANCELAPPOINMETFAILURE";


export const GETMYAPPOINTDATAREQ     = "GETMYAPPOINTDATAREQ";
export const GETMYAPPOINTDATASUCESS  = "GETMYAPPOINTDATASUCESS";
export const GETMYAPPOINTDATAFAILURE = "GETMYAPPOINTDATAFAILURE";


export const ALLAPPOINMENTREQ     = "GETMYAPPOINMENTREQ";
export const ALLAPPOINMENTSUCESS  = "GETMYAPPOINMENTSUCESS";
export const ALLAPPOINMENTFAILURE = "GETMYAPPOINMENTFAILURE";


export const POSTCOMMENTREQ     = "POSTCOMMENTREQ";
export const POSTCOMMENTSUCESS  = "POSTCOMMENTSUCESS";
export const POSTCOMMENTFAILURE = "POSTCOMMENTFAILURE";